<a href="https://colab.research.google.com/github/Niko0w0/colabNotebook/blob/main/numpy%2Bpandas%E4%BD%BF%E7%94%A8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

参考莫烦python的数据处理教程

In [1]:
pip install numpy

In [2]:
pip install pandas

In [ ]:
import numpy as np

array = np.array([[1,2,3], 
          [2,3,4]])
print(array)
print("number of dim:", array.ndim)
print("shape:", array.shape)
print("size", array.size)

[[1 2 3]
 [2 3 4]]
number of dim: 2
shape: (2, 3)
size 6


In [ ]:
import numpy as np

# a = np.array([2, 23, 4], dtype=np.int)
# a = np.array([2, 23, 4], dtype=np.float)
# print(a.dtype)

# a = np.zeros((3, 4))
# a = np.ones((3, 4))
# a = np.empty((3, 4))

# a = np.arange(10, 20, 2) # 生成从10-20，步长为2的数组
# a = np.arange(12).reshape((3, 4))

# a = np.linspace(1, 10, 6) # 开始，结束，需要分成多少端，自动生成符合要求的数列
a = np.linspace(1, 10, 6).reshape(2, 3)
print(a)

[[ 1.   2.8  4.6]
 [ 6.4  8.2 10. ]]


In [ ]:
import numpy as np

a = np.array([[1, 1],
        [0, 1]])
b = np.arange(4).reshape((2, 2))
# c = b ** 2
# c = 10 * np.sin(a) #a中所有值求sin后乘10
# print(c)
# print(b < 3)
# print(b == 3)
c = a * b
c_dot = np.dot(a, b)
print(c)
print(c_dot) # 矩阵运算
c_dot_2 = a.dot(b)
print(c_dot_2)

[[0 1]
 [0 3]]
[[2 4]
 [2 3]]
[[2 4]
 [2 3]]


In [ ]:
import numpy as np
a = np.random.random((2, 4))
print(a)
print(np.sum(a, axis=1)) # axis定义维度，0是对列操作，1是对行操作
print(np.min(a, axis=0))
print(np.max(a, axis=1))

[[0.36471326 0.66552975 0.22262649 0.69007644]
 [0.03445725 0.0133085  0.97442817 0.14506295]]
[1.94294594 1.16725686]
[0.03445725 0.0133085  0.22262649 0.14506295]
[0.69007644 0.97442817]


In [ ]:
import numpy as np
A = np.arange(2, 14).reshape(2, 6)

print(np.argmin(A)) # 最小的值的索引
print(np.argmax(A))
print(np.mean(A))
print(A.mean())
print(np.average(A))
print(np.median(A)) # 中位数
print(np.cumsum(A)) # 第几项就是前几项的和
print(np.diff(A)) # 求代表后一项与前一项的差
print(np.nonzero(A)) # 返回的是索引，行的索引以及列的索引
print(np.sort(A))
# 矩阵的转置
print(np.transpose(A)) 
print(A.T)
print((A.T).dot(A))

np.clip(A, 5, 9) # 将a中所有小于5的数改为5，所有大于9的数改为9，在之间的数不变

A = np.arange(14, 2, -1).reshape((3, 4))
print(A)
print(np.mean(A, axis=1))
print(np.mean(A, axis=0))

0
11
7.5
7.5
7.5
7.5
[ 2  5  9 14 20 27 35 44 54 65 77 90]
[[1 1 1 1 1]
 [1 1 1 1 1]]
(array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1]), array([0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5]))
[[ 2  3  4  5  6  7]
 [ 8  9 10 11 12 13]]
[[ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]
 [ 6 12]
 [ 7 13]]
[[ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]
 [ 6 12]
 [ 7 13]]
[[ 68  78  88  98 108 118]
 [ 78  90 102 114 126 138]
 [ 88 102 116 130 144 158]
 [ 98 114 130 146 162 178]
 [108 126 144 162 180 198]
 [118 138 158 178 198 218]]
[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
[12.5  8.5  4.5]
[10.  9.  8.  7.]


In [ ]:
import numpy as np

A = np.arange(3, 15).reshape((3,4))
print(A)
print(A[2][1])
print(A[2,1])

for row in A:
  print(row)
for column in A.T:
  print(column)

print(A.flat) # 把A转变为只有一行的数组
print(A.flatten)
for item in A.flat:
  print(item)

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
12
12
[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]
[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]
<built-in method flatten of numpy.ndarray object at 0x7fb7c1586c30>
3
4
5
6
7
8
9
10
11
12
13
14


In [ ]:
import numpy as np
A = np.array([1,1,1])
B = np.array([2,2,2])
# vertical stack进行一个上下的合并
C = np.vstack((A,B))
# horizontal stack进行左右合并
D = np.hstack((A,B))
print(C)
print(D)
print(A.shape, B.shape, C.shape, D.shape)

# 加维度
print(A[np.newaxis, :])
print(A[:, np.newaxis])

A = np.array([1,1,1])[:,np.newaxis]
B = np.array([2,2,2])[:,np.newaxis]

C = np.concatenate((A,B,B,A),axis=0) # 进行多个array的合并 axis为0表示在横向，1表示在纵向
print(C)

[[1 1 1]
 [2 2 2]]
[1 1 1 2 2 2]
(3,) (3,) (2, 3) (6,)
[[1 1 1]]
[[1]
 [1]
 [1]]
[[1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [1]
 [1]
 [1]]


[how to use numpy中的newaxis](https://stackoverflow.com/questions/29241056/how-does-numpy-newaxis-work-and-when-to-use-it)

In [ ]:
# numpy的array分割
import numpy as np

A = np.arange(12).reshape((3,4))
print(A)

# axis=0,对行操作，行数改变 axis=1，对列操作，列数改变
# 只能进行相等块数的分隔，不能进行不等量的分隔
print(np.split(A, 2, axis=1)) # 对其进行纵向分隔，分成两块
print(np.split(A, 3, axis=0))

# array_split进行不等量的分隔
print(np.array_split(A, 3, axis=1))

print(np.vsplit(A,3))
print(np.hsplit(A,2))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


In [ ]:
# numpy的copy & deep copy
import numpy as np

a = np.arange(4)
print(a)
b = a
c = a
d = b
a[0] = 11
print(a, b, c, d)
print(b is a) # is比较对象的地址 ==比较对象的值
d[1:3] = [22, 33]
print(a)

b = a.copy() # deep copy
a[3] = 44
print(a, b)

[0 1 2 3]
[11  1  2  3] [11  1  2  3] [11  1  2  3] [11  1  2  3]
True
[11 22 33  3]
[11 22 33 44] [11 22 33  3]


In [ ]:
# pandas 基本介绍
import pandas as pd
import numpy as np

s = pd.Series([1, 3, 6, np.nan, 44, 1])
print(s)

dates = pd.date_range('20220513',periods=6)
print(dates)

df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=['a','b','c','d'])
print(df)

df1 = pd.DataFrame(np.arange(12).reshape((3,4)))
print(df1)

df2 = pd.DataFrame({'A':1.,
          'B':pd.Timestamp('20220513'),
          'C':pd.Series(1,index=list(range(4)), dtype='float32'),
          'D':np.array([3]*4, dtype='int32'),
          'E':pd.Categorical(["test","train","test","train"]),
          'F':'foo'})
print(df2)
print(df2.dtypes)
print(df2.index)
print(df2.columns)
print(df2.values)
print(df2.describe())

print(df2.sort_index(axis=1,ascending=False)) # 倒序排列
print(df2.sort_index(axis=0,ascending=False))
print(df2.sort_values(by='E'))

0     1.0
1     3.0
2     6.0
3     NaN
4    44.0
5     1.0
dtype: float64
DatetimeIndex(['2022-05-13', '2022-05-14', '2022-05-15', '2022-05-16',
               '2022-05-17', '2022-05-18'],
              dtype='datetime64[ns]', freq='D')
                   a         b         c         d
2022-05-13  0.481928 -0.194874 -0.059614  1.123530
2022-05-14  0.307261 -0.193799 -1.708245 -1.405982
2022-05-15  0.689337 -2.051369 -1.097654 -0.971010
2022-05-16 -0.694788  0.031832 -0.182853  0.026402
2022-05-17  0.657991  1.057125 -0.001842 -0.209189
2022-05-18  1.162364  1.049848 -0.906736  0.546814
   0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11
     A          B    C  D      E    F
0  1.0 2022-05-13  1.0  3   test  foo
1  1.0 2022-05-13  1.0  3  train  foo
2  1.0 2022-05-13  1.0  3   test  foo
3  1.0 2022-05-13  1.0  3  train  foo
A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object
Int64Index([0, 1,

In [ ]:
# Pandas数据的筛选
import pandas as pd
import numpy as np

dates = pd.date_range('20220513',periods=6)
df = pd.DataFrame(np.arange(24).reshape((6,4)), index=dates, columns=['A','B','C','D'])
print(df)
print(df['A'], df.A)
print(df[0:3])
print(df['20220513':'20220517'])

# select by label:loc
print(df.loc['20220513'])
print(df.loc[:,['A','B']])

# select by position:iloc
print(df.iloc[3])
print(df.iloc[[1,3,5],1:3])

# mixed selection:ix
# 已被废弃
# print(df.ix[:3, ['A','C']])

# Boolean indexing
print(df[df.A > 8])

             A   B   C   D
2022-05-13   0   1   2   3
2022-05-14   4   5   6   7
2022-05-15   8   9  10  11
2022-05-16  12  13  14  15
2022-05-17  16  17  18  19
2022-05-18  20  21  22  23
2022-05-13     0
2022-05-14     4
2022-05-15     8
2022-05-16    12
2022-05-17    16
2022-05-18    20
Freq: D, Name: A, dtype: int64 2022-05-13     0
2022-05-14     4
2022-05-15     8
2022-05-16    12
2022-05-17    16
2022-05-18    20
Freq: D, Name: A, dtype: int64
            A  B   C   D
2022-05-13  0  1   2   3
2022-05-14  4  5   6   7
2022-05-15  8  9  10  11
             A   B   C   D
2022-05-13   0   1   2   3
2022-05-14   4   5   6   7
2022-05-15   8   9  10  11
2022-05-16  12  13  14  15
2022-05-17  16  17  18  19
A    0
B    1
C    2
D    3
Name: 2022-05-13 00:00:00, dtype: int64
             A   B
2022-05-13   0   1
2022-05-14   4   5
2022-05-15   8   9
2022-05-16  12  13
2022-05-17  16  17
2022-05-18  20  21
A    12
B    13
C    14
D    15
Name: 2022-05-16 00:00:00, dtype: int64
          

In [ ]:
# Pandas设置值
import pandas as pd
import numpy as np

dates = pd.date_range('20220513',periods=6)
df = pd.DataFrame(np.arange(24).reshape((6,4)), index=dates, columns=['A','B','C','D'])

df.iloc[2,2] = 1111
df.loc['20220513', 'B'] = 2222
df.B[df.A>4] = 0
df['F'] = np.nan
df['E'] = pd.Series([1,2,3,4,5,6], index=pd.date_range('20220513', periods=6))
print(df)

             A     B     C   D   F  E
2022-05-13   0  2222     2   3 NaN  1
2022-05-14   4     5     6   7 NaN  2
2022-05-15   8     0  1111  11 NaN  3
2022-05-16  12     0    14  15 NaN  4
2022-05-17  16     0    18  19 NaN  5
2022-05-18  20     0    22  23 NaN  6


In [ ]:
# Pandas处理丢失数据
import pandas as pd
import numpy as np

dates = pd.date_range('20220513',periods=6)
df = pd.DataFrame(np.arange(24).reshape((6,4)), index=dates, columns=['A','B','C','D'])
df.iloc[0,1] = np.nan
df.iloc[1,2] = np.nan

print(df.dropna(axis=0, how="any")) # how={'any', 'all'} all表示只有在这一行或者列（看axis的值判断是行或列）都是nan的时候才丢掉
print(df.dropna(axis=1, how="any"))

print(df.fillna(value=0))
print(np.any(df.isnull())==True)

             A     B     C   D
2022-05-15   8   9.0  10.0  11
2022-05-16  12  13.0  14.0  15
2022-05-17  16  17.0  18.0  19
2022-05-18  20  21.0  22.0  23
             A   D
2022-05-13   0   3
2022-05-14   4   7
2022-05-15   8  11
2022-05-16  12  15
2022-05-17  16  19
2022-05-18  20  23
             A     B     C   D
2022-05-13   0   0.0   2.0   3
2022-05-14   4   5.0   0.0   7
2022-05-15   8   9.0  10.0  11
2022-05-16  12  13.0  14.0  15
2022-05-17  16  17.0  18.0  19
2022-05-18  20  21.0  22.0  23
True


In [4]:
# Pandas导入导出数据
import pandas as pd
import numpy as np
# data = pd.read_csv('') # 里面写文件名
# 没有文件故不演示
# concatenating
df1 = pd.DataFrame(np.ones((3,4)) * 0, columns = ['a', 'b', 'c', 'd'])
df2 = pd.DataFrame(np.ones((3,4)) * 1, columns = ['a', 'b', 'c', 'd'])
df3 = pd.DataFrame(np.ones((3,4)) * 2, columns = ['a', 'b', 'c', 'd'])
print(df1)
print(df1)
print(df3)
res = pd.concat([df1, df2, df3], axis=0, ignore_index=True)
print(res)

# join, ['inner', 'outer']
df1 = pd.DataFrame(np.ones((3,4)) * 0, columns = ['a', 'b', 'c', 'd'], index=[1,2,3])
df2 = pd.DataFrame(np.ones((3,4)) * 1, columns = ['b', 'c', 'd', 'e'], index=[2,3,4])
print(df1)
print(df2)
res = pd.concat([df1, df2], join='outer') # 默认为outer
print(res)
res = pd.concat([df1, df2], join='inner')
print(res)
res = pd.concat([df1, df2], join='inner', ignore_index=True)
print(res)

     a    b    c    d
0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0
     a    b    c    d
0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0
     a    b    c    d
0  2.0  2.0  2.0  2.0
1  2.0  2.0  2.0  2.0
2  2.0  2.0  2.0  2.0
     a    b    c    d
0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0
3  1.0  1.0  1.0  1.0
4  1.0  1.0  1.0  1.0
5  1.0  1.0  1.0  1.0
6  2.0  2.0  2.0  2.0
7  2.0  2.0  2.0  2.0
8  2.0  2.0  2.0  2.0
     a    b    c    d
1  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0
3  0.0  0.0  0.0  0.0
     b    c    d    e
2  1.0  1.0  1.0  1.0
3  1.0  1.0  1.0  1.0
4  1.0  1.0  1.0  1.0
     a    b    c    d    e
1  0.0  0.0  0.0  0.0  NaN
2  0.0  0.0  0.0  0.0  NaN
3  0.0  0.0  0.0  0.0  NaN
2  NaN  1.0  1.0  1.0  1.0
3  NaN  1.0  1.0  1.0  1.0
4  NaN  1.0  1.0  1.0  1.0
     b    c    d
1  0.0  0.0  0.0
2  0.0  0.0  0.0
3  0.0  0.0  0.0
2  1.0  1.0  1.0
3  1.0  1.0  1.0
4  1.0  1.0  1.0
     b    c    d
0  0.0  0.0  0.

In [5]:
# join_axes
df1 = pd.DataFrame(np.ones((3,4)) * 0, columns = ['a', 'b', 'c', 'd'], index=[1,2,3])
df2 = pd.DataFrame(np.ones((3,4)) * 1, columns = ['b', 'c', 'd', 'e'], index=[2,3,4])
res = pd.concat([df1,df2], axis=1).iloc[[0,1,2]]
print(res)

res = df1.append(df2, ignore_index=True)
print(res)


df1 = pd.DataFrame(np.ones((3,4)) * 0, columns = ['a', 'b', 'c', 'd'])
df2 = pd.DataFrame(np.ones((3,4)) * 1, columns = ['a', 'b', 'c', 'd'])
df3 = pd.DataFrame(np.ones((3,4)) * 2, columns = ['a', 'b', 'c', 'd'])
res = df1.append([df2, df3], ignore_index=True)
print(res)

     a    b    c    d    b    c    d    e
1  0.0  0.0  0.0  0.0  NaN  NaN  NaN  NaN
2  0.0  0.0  0.0  0.0  1.0  1.0  1.0  1.0
3  0.0  0.0  0.0  0.0  1.0  1.0  1.0  1.0
     a    b    c    d    e
0  0.0  0.0  0.0  0.0  NaN
1  0.0  0.0  0.0  0.0  NaN
2  0.0  0.0  0.0  0.0  NaN
3  NaN  1.0  1.0  1.0  1.0
4  NaN  1.0  1.0  1.0  1.0
5  NaN  1.0  1.0  1.0  1.0
     a    b    c    d
0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0
3  1.0  1.0  1.0  1.0
4  1.0  1.0  1.0  1.0
5  1.0  1.0  1.0  1.0
6  2.0  2.0  2.0  2.0
7  2.0  2.0  2.0  2.0
8  2.0  2.0  2.0  2.0


In [7]:
# Pandas合并 merge
import pandas as pd
import numpy as np

left = pd.DataFrame({'key':['K0','K1','K2','K3'],
            'A':['A0','A1','A2','A3'],
            'B':['B0','B1','B2','B3']})
right = pd.DataFrame({'key':['K0','K1','K2','K3'],
            'C':['C0','C1','C2','C3'],
            'D':['D0','D1','D2','D3']})

# merging two df by key/keys. (may be used in database)
# consider two keys
print(left)
print(right)
res = pd.merge(left, right, on='key')
print(res)

  key   A   B
0  K0  A0  B0
1  K1  A1  B1
2  K2  A2  B2
3  K3  A3  B3
  key   C   D
0  K0  C0  D0
1  K1  C1  D1
2  K2  C2  D2
3  K3  C3  D3
  key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3


In [10]:
left = pd.DataFrame({'key1':['K0','K1','K2','K3'],
            'key2':['K0','K1','K2','K3'],
            'A':['A0','A1','A2','A3'],
            'B':['B0','B1','B2','B3']})
right = pd.DataFrame({'key1':['K0','K1','K2','K3'],
            'key2':['K0','K1','K2','K3'],
            'C':['C0','C1','C2','C3'],
            'D':['D0','D1','D2','D3']})

# merging two df by key/keys. (may be used in database)
# consider two keys
print(left)
print(right)
# how = ['left', 'right', 'outer', 'inner']
res = pd.merge(left, right, on=['key1','key2']) # 默认合并方法为inner
print(res)

  key1 key2   A   B
0   K0   K0  A0  B0
1   K1   K1  A1  B1
2   K2   K2  A2  B2
3   K3   K3  A3  B3
  key1 key2   C   D
0   K0   K0  C0  D0
1   K1   K1  C1  D1
2   K2   K2  C2  D2
3   K3   K3  C3  D3
  key1 key2   A   B   C   D
0   K0   K0  A0  B0  C0  D0
1   K1   K1  A1  B1  C1  D1
2   K2   K2  A2  B2  C2  D2
3   K3   K3  A3  B3  C3  D3
